# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_server', '0003_auto_20160403_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='text',
            new_name='name',
        ),
    ]
