# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo_server', '0004_auto_20160403_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
